//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFabric.Admin.Service.DataAccess.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFabric.Admin.Service.DataAccess.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command null or empty..
        /// </summary>
        internal static string CommandNullOrEmpty {
            get {
                return ResourceManager.GetString("CommandNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName null or empty..
        /// </summary>
        internal static string HostNameNullOrEmpty {
            get {
                return ResourceManager.GetString("HostNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache name..
        /// </summary>
        internal static string InvalidCacheName {
            get {
                return ResourceManager.GetString("InvalidCacheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache port must be greater that 1024..
        /// </summary>
        internal static string InvalidCachePort {
            get {
                return ResourceManager.GetString("InvalidCachePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientAccount null or empty..
        /// </summary>
        internal static string InvalidClientAccount {
            get {
                return ResourceManager.GetString("InvalidClientAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any hosts in the cluster..
        /// </summary>
        internal static string InvalidCluster {
            get {
                return ResourceManager.GetString("InvalidCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fileName..
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument for formatter {0}..
        /// </summary>
        internal static string InvalidFormatterArgument {
            get {
                return ResourceManager.GetString("InvalidFormatterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the host name is specified, the cache port should be specified..
        /// </summary>
        internal static string InvalidHostPort {
            get {
                return ResourceManager.GetString("InvalidHostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve any statistic about the cluster..
        /// </summary>
        internal static string NoClusterStatistics {
            get {
                return ResourceManager.GetString("NoClusterStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred when executing a PowerShell command..
        /// </summary>
        internal static string PSCommandFailed {
            get {
                return ResourceManager.GetString("PSCommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following errors occurred when executing command {0} :
        ///{1}.
        /// </summary>
        internal static string WarnPsErrors {
            get {
                return ResourceManager.GetString("WarnPsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following warnings occurred when executing command {0} :
        ///{1}.
        /// </summary>
        internal static string WarnPsWarnings {
            get {
                return ResourceManager.GetString("WarnPsWarnings", resourceCulture);
            }
        }
    }
}
