//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFabric.Admin.Clients.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFabric.Admin.Clients.Desktop.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutProduct {
            get {
                return ResourceManager.GetString("AboutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string AdministrationContextMenuHeader {
            get {
                return ResourceManager.GetString("AdministrationContextMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string AdministrationRibbonHeader {
            get {
                return ResourceManager.GetString("AdministrationRibbonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string BackstageHeader {
            get {
                return ResourceManager.GetString("BackstageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Hosts.
        /// </summary>
        internal static string CacheHostsFolderTitle {
            get {
                return ResourceManager.GetString("CacheHostsFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Key.
        /// </summary>
        internal static string CacheKeyHeader {
            get {
                return ResourceManager.GetString("CacheKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string ClusterHealthHeader {
            get {
                return ResourceManager.GetString("ClusterHealthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        internal static string ClusterRibbonGroupBoxHeader {
            get {
                return ResourceManager.GetString("ClusterRibbonGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A question ?
        ///Send your feedback on our forums..
        /// </summary>
        internal static string ContactUsDescription {
            get {
                return ResourceManager.GetString("ContactUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthieu Klotz.
        /// </summary>
        internal static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors :.
        /// </summary>
        internal static string ContributorsLabel {
            get {
                return ResourceManager.GetString("ContributorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHeader {
            get {
                return ResourceManager.GetString("DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters :.
        /// </summary>
        internal static string EnvironmentClusters {
            get {
                return ResourceManager.GetString("EnvironmentClusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string EnvironmentDescription {
            get {
                return ResourceManager.GetString("EnvironmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string EnvironmentName {
            get {
                return ResourceManager.GetString("EnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        internal static string EnvironmentsHeader {
            get {
                return ResourceManager.GetString("EnvironmentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to configure your client or server
        ///of the administration tool..
        /// </summary>
        internal static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HeaderClusterName {
            get {
                return ResourceManager.GetString("HeaderClusterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Service URI.
        /// </summary>
        internal static string HeaderClusterUri {
            get {
                return ResourceManager.GetString("HeaderClusterUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string HeaderClusterUserName {
            get {
                return ResourceManager.GetString("HeaderClusterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        internal static string HeaderClusterUserPassword {
            get {
                return ResourceManager.GetString("HeaderClusterUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Status for {0}.
        /// </summary>
        internal static string HealthTabItemHeader {
            get {
                return ResourceManager.GetString("HealthTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Host.
        /// </summary>
        internal static string HostsRibbonGroupBoxHeader {
            get {
                return ResourceManager.GetString("HostsRibbonGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        internal static string MonitoringContextMenuHeader {
            get {
                return ResourceManager.GetString("MonitoringContextMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        internal static string MonitoringHeader {
            get {
                return ResourceManager.GetString("MonitoringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about version, license and copyright..
        /// </summary>
        internal static string MoreInfoAboutLicense {
            get {
                return ResourceManager.GetString("MoreInfoAboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Cache.
        /// </summary>
        internal static string NamedCacheHeader {
            get {
                return ResourceManager.GetString("NamedCacheHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Caches.
        /// </summary>
        internal static string NamedCachesFolderTitle {
            get {
                return ResourceManager.GetString("NamedCachesFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Cache :.
        /// </summary>
        internal static string NamedCacheTitle {
            get {
                return ResourceManager.GetString("NamedCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors :.
        /// </summary>
        internal static string ProductContributors {
            get {
                return ResourceManager.GetString("ProductContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to :.
        /// </summary>
        internal static string ProductSpecialThanks {
            get {
                return ResourceManager.GetString("ProductSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version :.
        /// </summary>
        internal static string ProductVersion {
            get {
                return ResourceManager.GetString("ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string RegionHeader {
            get {
                return ResourceManager.GetString("RegionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a bug ?
        ///Let us know and we will correct it..
        /// </summary>
        internal static string ReportBugDescription {
            get {
                return ResourceManager.GetString("ReportBugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        internal static string ReportBugTitle {
            get {
                return ResourceManager.GetString("ReportBugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string RestartHeader {
            get {
                return ResourceManager.GetString("RestartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchHeader {
            get {
                return ResourceManager.GetString("SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Key Pattern :.
        /// </summary>
        internal static string SearchPatternTitle {
            get {
                return ResourceManager.GetString("SearchPatternTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in {0}.
        /// </summary>
        internal static string SearchTabItemHeader {
            get {
                return ResourceManager.GetString("SearchTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors :.
        /// </summary>
        internal static string SponsorsLabel {
            get {
                return ResourceManager.GetString("SponsorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartHeader {
            get {
                return ResourceManager.GetString("StartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticsHeader {
            get {
                return ResourceManager.GetString("StatisticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for {0}.
        /// </summary>
        internal static string StatsTabItemHeader {
            get {
                return ResourceManager.GetString("StatsTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopHeader {
            get {
                return ResourceManager.GetString("StopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string SupportTitle {
            get {
                return ResourceManager.GetString("SupportTitle", resourceCulture);
            }
        }
    }
}
